# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "azure_iot_operations_mqtt"
version = "0.9.0"
edition = "2024"
license = "MIT"
description = "MQTT version 5.0 client library providing flexibility for decoupled asynchronous applications"
repository = "https://github.com/Azure/iot-operations-sdks"
readme = "README.md"
publish = true

[dependencies]
anyhow = "1.0.86"                                                                   # TODO: reconsider inclusion once TLS library is finalized
async-trait = "0.1.81"
bytes.workspace = true
derive_builder.workspace = true
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
futures = "0.3.31"
log.workspace = true
notify = "7"
notify-debouncer-full = "0.4.0"
openssl = "0.10.66"                                                                 # only used with rumqttc to set up TLS settings
rand = "0.8.5"
rumqttc = { version = "0.24.0-fork.4", registry = 'aio-sdks', default-features = false, features = ["use-native-tls"]}
client = {path = "../../../mqtt-rust/client"}
codec = { path = "../../../mqtt-rust/codec" }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
azure_iot_operations_mqtt = { path = ".", features = ["test-utils"] }
env_logger.workspace = true
temp-env = "0.3.6"
tempfile = "3.19.1"
test-case.workspace = true
tokio-test.workspace = true

[features]
test-utils = []

[lints]
workspace = true
